const ANALYSE_SENTENCES = "ANALYSE_SENTENCES"
const ANALYSE_SENTENCES_SUCCESS = "ANALYSE_SENTENCES_SUCCESS"
const ANALYSE_SENTENCES_FAIL = "ANALYSE_SENTENCES_FAIL"

export default {
  ANALYSE_SENTENCES,
  ANALYSE_SENTENCES_SUCCESS,
  ANALYSE_SENTENCES_FAIL
}
